<?php
$config = \Suggestotron\Config::get('site');
?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/img/favicon.png">

    <title><?php echo $config['title'];?></title>

    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
	<link href="/css/bootstrap-theme.min.css" rel="stylesheet">
	<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
	<!-- Bootstrap core JavaScript
    ================================================= -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="/js/jquery-1.10.2.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project Template</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/topic/list">Home</a></li>
            <li><a href="/about/info">About</a></li>
          </ul>
		  <form class="navbar-form navbar-right" role="search">
                            <a href="/topic/add" class="btn btn-sm btn-default">
                                <span class="glyphicon glyphicon-plus-sign"></span>
                                Add Topic
                            </a>
                        </form>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
	  <div style="margin-top:60px"></div>
      <?php $this->content(); ?>

    </div><!-- /.container -->
  </body>
</html>
