<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title"><span class="glyphicon glyphicon-plus-sign"></span>&nbspAdd Topic</h3>
    </div>
    <div class="panel-body">
<form action="https://localhost/example/public/v1/topics" method="POST">
    <label>
        Title: <input class="input input-sm" type="text" name="title">
    </label>
    <br>
    <label>
        Description:
        <br>
        <textarea class="input input-sm" name="description" cols="70" rows="10"></textarea>
    </label>
    <br>
    <button type="submit" class="btn btn-primary"><i class="fa fa-plus-circle"></i>&nbspAdd Topic</button>
</form>
    </div>
</div>