<?php
$topic = $this->topic;
?>
<div class="panel panel-info">
    <div class="panel-heading">
        <h3 class="panel-title"><span class="glyphicon glyphicon-edit"></span>&nbspEdit Topic</h3>
    </div>
    <div class="panel-body">
<form action="http://localhost/example/public/v1/topics/<?php echo $topic['id'];?>" method="POST">
	<input type="hidden" name="_METHOD" value="put" />
    <label>
        Title: <input class="input input-sm" type="text" name="title" value="<?php echo $topic['title'];?>">
    </label>
    <br>
    <label>
        Description:
        <br>
        <textarea class="input input-sm" name="description" cols="70" rows="10"><?php echo $topic['description'];?></textarea>
    </label>
    <br>
    <input type="hidden" name="id" value="<?php echo $topic['id'];?>">
    <button type="submit" class="btn btn-primary"><i class="fa fa-edit"></i>&nbspEdit Topic</button>
</form>
    </div>
</div>
