<?php
$topics = $this->topics;
$message = $this->message;
switch($message){
case 0:break;
case 1:
?>
<div class="alert alert-success" role="alert">
        <strong>Well done!</strong> You successfully adding the topics.
</div>
<?php
	break;
case 2:
?>
<div class="alert alert-success" role="alert">
        <strong>Well done!</strong> You successfully edit the topics.
</div>
<?php
	break;
case 3:
?>
<div class="alert alert-success" role="alert">
        <strong>Well done!</strong> You successfully delete the topics.
</div>
<?php
	break;
case 99:
?>
<div class="alert alert-danger" role="alert">
        <strong>Oops!</strong> An error occured.
</div>
<?php
	break;
}
foreach ($topics as $topic) {
    ?>
    <section>
        <div class="row">
            <div class="col-xs-12">
                <h3><?php echo $topic['title'];?></h3>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-8">
                <p class="text-muted">
                    <?php echo nl2br($topic['description']);?>
                </p>
            </div>
            <div class="col-xs-4">
                <p class="pull-right">
		    <a href="/vote/add/<?php echo $topic['id']; ?>" class="btn btn-sm btn-success">
		        <span class="glyphicon glyphicon-thumbs-up">
		            <strong><?php echo (isset($topic['count'])) ? $topic['count'] : 0;?></strong>
		        </span>
		    </a>
                    <a href="/topic/edit/<?php echo $topic['id']; ?>" class="btn btn-sm btn-primary"><i class="fa fa-edit"></i><strong>&nbsp Edit</strong></a>
                    <a href="/topic/delete/<?php echo $topic['id']; ?>" class="btn btn-sm btn-danger" data-container="body" data-toggle="popover" data-trigger="hover" data-placement="top" data-title="Are you sure?" data-content=" This cannot be undone!"><i class="fa fa-times-circle-o"></i><strong>&nbsp Delete</strong></a>
		</p>
            </div>
        </div>
    </section>	
    <hr>
    <?php
}
?>
<script type="text/javascript">
        $(function () {
           	$('[data-toggle="popover"]').popover();
        });
</script>